window.CL_DATA = (function () {
  const thumb = (alt) => ({ src: "thumb.jpg", alt });
  const videos = [
    {
      id: "v-copy",
      title: "Why Copy Trading Doesn't Work Like You Think",
      channel: "SignalDesk",
      subs: 84200,
      age: "2d",
      duration: "12:18",
      type: "Long-form",
      views: 98400,
      viewsDay: 49200,
      viewsHour: 2050,
      likes: 6100,
      comments: 842,
      engagement: 7.1,
      outlier: 6.8,
      topic: "Copy Trading",
      published: "2 days ago",
      baseline: 14500,
      opportunity: 91,
      momentum: "High",
    },
    {
      id: "v-ai24",
      title: "I Built an AI App in 24 Hours",
      channel: "BuildFast",
      subs: 61200,
      age: "18h",
      duration: "14:02",
      type: "Long-form",
      views: 148312,
      viewsDay: 197000,
      viewsHour: 8217,
      likes: 9200,
      comments: 1402,
      engagement: 7.8,
      outlier: 8.4,
      topic: "AI building",
      published: "18 hours ago",
      baseline: 17600,
      opportunity: 94,
      momentum: "Extreme",
    },
    {
      id: "v-signals",
      title: "Why Most Trading Signals Fail",
      channel: "RiskDesk",
      subs: 121000,
      age: "3d",
      duration: "9:41",
      type: "Long-form",
      views: 81200,
      viewsDay: 27066,
      viewsHour: 1127,
      likes: 4100,
      comments: 611,
      engagement: 5.8,
      outlier: 4.9,
      topic: "Trading psychology",
      published: "3 days ago",
      baseline: 16600,
      opportunity: 82,
      momentum: "Strong",
    },
    {
      id: "v-journal",
      title: "I Built an AI Trading Journal in 7 Days",
      channel: "DeskCraft",
      subs: 33400,
      age: "22h",
      duration: "11:05",
      type: "Long-form",
      views: 61200,
      viewsDay: 66800,
      viewsHour: 2781,
      likes: 3800,
      comments: 490,
      engagement: 7.0,
      outlier: 7.2,
      topic: "AI tools",
      published: "22 hours ago",
      baseline: 8500,
      opportunity: 88,
      momentum: "High",
    },
    {
      id: "v-shorts",
      title: "Why Your YouTube Shorts Stop at 500 Views",
      channel: "Creator Math",
      subs: 98000,
      age: "9h",
      duration: "0:48",
      type: "Short",
      views: 412000,
      viewsDay: 1098666,
      viewsHour: 45777,
      likes: 28400,
      comments: 1902,
      engagement: 7.4,
      outlier: 11.3,
      topic: "Creator growth",
      published: "9 hours ago",
      baseline: 36400,
      opportunity: 96,
      momentum: "Extreme",
    },
    {
      id: "v-agents",
      title: "I Tested AI Agents for 30 Days",
      channel: "ShipWeekly",
      subs: 54000,
      age: "4d",
      duration: "16:22",
      type: "Long-form",
      views: 73400,
      viewsDay: 18350,
      viewsHour: 764,
      likes: 5100,
      comments: 720,
      engagement: 7.9,
      outlier: 5.1,
      topic: "AI agents",
      published: "4 days ago",
      baseline: 14400,
      opportunity: 79,
      momentum: "Strong",
    },
    {
      id: "v-risk",
      title: "5 Risk Management Mistakes Beginners Make",
      channel: "RiskDesk",
      subs: 121000,
      age: "6d",
      duration: "8:14",
      type: "Long-form",
      views: 42800,
      viewsDay: 7133,
      viewsHour: 297,
      likes: 2100,
      comments: 310,
      engagement: 5.6,
      outlier: 2.4,
      topic: "Risk management",
      published: "6 days ago",
      baseline: 17800,
      opportunity: 64,
      momentum: "Interesting",
    },
    {
      id: "v-saas",
      title: "How I Built a SaaS With Zero Experience",
      channel: "Build in Public Club",
      subs: 41000,
      age: "1d",
      duration: "13:40",
      type: "Long-form",
      views: 39200,
      viewsDay: 39200,
      viewsHour: 1633,
      likes: 2400,
      comments: 388,
      engagement: 7.1,
      outlier: 4.1,
      topic: "Build in public",
      published: "1 day ago",
      baseline: 9600,
      opportunity: 77,
      momentum: "Strong",
    },
    {
      id: "v-code",
      title: "This Tiny Coding Project Got Me Interviews",
      channel: "Junior Path",
      subs: 27600,
      age: "5d",
      duration: "10:02",
      type: "Long-form",
      views: 51800,
      viewsDay: 10360,
      viewsHour: 431,
      likes: 3300,
      comments: 512,
      engagement: 7.4,
      outlier: 3.6,
      topic: "Programming",
      published: "5 days ago",
      baseline: 14400,
      opportunity: 71,
      momentum: "Interesting",
    },
    {
      id: "v-ai-only",
      title: "I Tried Building an App With AI Only",
      channel: "BuildFast",
      subs: 61200,
      age: "8d",
      duration: "15:11",
      type: "Long-form",
      views: 88400,
      viewsDay: 11050,
      viewsHour: 460,
      likes: 5400,
      comments: 801,
      engagement: 7.0,
      outlier: 5.0,
      topic: "AI building",
      published: "8 days ago",
      baseline: 17600,
      opportunity: 74,
      momentum: "Strong",
    },
  ];

  videos.forEach((v) => {
    v.thumbAlt = `YouTube thumbnail for ${v.title}`;
    v.viewsSub = +(v.views / v.subs).toFixed(2);
  });

  const ideas = [
    {
      id: "idea-004",
      title: "Why Two Traders Copying the Same Signal Get Different Results",
      hook: "Same signal. Same entry. Completely different result.",
      topic: "Copy Trading",
      type: "Short",
      sources: 3,
      priority: "High",
      created: "Sep 12",
      status: "Published",
      hypothesis:
        "Contradiction-based trading hooks appear to outperform standard educational hooks.",
      angle: "Surprising problem, not a tutorial",
      audience: "Retail traders who copy signals",
    },
    {
      id: "idea-ai",
      title: "I Built a Tiny AI Research Desk in One Evening",
      hook: "No team. No stack. Just one focused experiment.",
      topic: "AI building",
      type: "Long-form",
      sources: 2,
      priority: "High",
      created: "Sep 15",
      status: "Ready",
      hypothesis: "Challenge + time constraint titles are converting on similar channels.",
      angle: "Visible result in 24 hours",
      audience: "Indie hackers",
    },
    {
      id: "idea-shorts",
      title: "The Real Reason Shorts Die at 500 Views",
      hook: "It isn't the algorithm. It's the first 1.5 seconds.",
      topic: "Creator growth",
      type: "Short",
      sources: 1,
      priority: "Med",
      created: "Sep 16",
      status: "Researching",
      hypothesis: "Mistake-pattern hooks work when paired with a concrete diagnosis.",
      angle: "Creator math, not motivation",
      audience: "Small YouTube channels",
    },
    {
      id: "idea-risk",
      title: "The Position Size That Quietly Blows Up Accounts",
      hook: "Your strategy is fine. Your size is not.",
      topic: "Risk management",
      type: "Long-form",
      sources: 2,
      priority: "Med",
      created: "Sep 10",
      status: "Inbox",
      hypothesis: "Beginner mistake lists still work if the first item is unexpected.",
      angle: "One lethal mistake, not five",
      audience: "New traders",
    },
    {
      id: "idea-bip",
      title: "Shipping in Public Without Performing for the Camera",
      hook: "Build in public is useful. Performing is not.",
      topic: "Build in public",
      type: "Long-form",
      sources: 1,
      priority: "Low",
      created: "Sep 8",
      status: "Recorded",
      hypothesis: "Honest process videos convert better than highlight reels for this audience.",
      angle: "Anti-performance",
      audience: "Builders",
    },
    {
      id: "idea-agents",
      title: "What 30 Days of AI Agents Actually Changed",
      hook: "I expected speed. I got a different bottleneck.",
      topic: "AI agents",
      type: "Long-form",
      sources: 2,
      priority: "Med",
      created: "Sep 17",
      status: "Analyzing",
      hypothesis: "Unexpected-result hooks outperform pure challenge videos for agents.",
      angle: "Bottleneck, not magic",
      audience: "Builders using AI tools",
    },
  ];

  const experiments = [
    {
      id: "EXP-004",
      name: "Contradiction hook on copy trading",
      ideaId: "idea-004",
      videoId: "cv-004",
      topic: "Copy Trading",
      format: "Short",
      hypothesis:
        "Contradiction-based trading hooks appear to outperform standard educational hooks.",
      published: "Sep 14",
      v24: 7420,
      v7: 18640,
      retention: 71,
      subs: 38,
      result: "Strong 24h, solid conversion",
      decision: "GO",
      lesson:
        "Trading education performs better when framed around a surprising problem rather than a tutorial.",
      next: "Use the same hook structure with a product-building topic.",
      status: "Published",
    },
    {
      id: "EXP-003",
      name: "Why copied signals give different results",
      ideaId: "idea-004",
      videoId: "cv-003",
      topic: "Trading psychology",
      format: "Long-form",
      hypothesis: "Copied-signal framing creates curiosity without promising a system.",
      published: "Sep 7",
      v24: 6800,
      v7: 15420,
      retention: 64,
      subs: 22,
      result: "Promising, needs a second run",
      decision: "TEST",
      lesson: "Contradiction hooks worked; subscriber conversion was lower than build-in-public.",
      next: "Keep the hook, change the topic to product building.",
      status: "Published",
    },
    {
      id: "EXP-002",
      name: "AI challenge in 24 hours",
      ideaId: "idea-ai",
      videoId: "cv-002",
      topic: "AI building",
      format: "Long-form",
      hypothesis: "Time-boxed build videos create curiosity and a visible result.",
      published: "Aug 28",
      v24: 4120,
      v7: 9800,
      retention: 58,
      subs: 11,
      result: "Market loves it; Christina conversion is mixed",
      decision: "TEST",
      lesson: "AI challenge videos look Strong in the market but TEST for this channel.",
      next: "Keep challenge format, tighten first 20 seconds.",
      status: "Published",
    },
    {
      id: "EXP-001",
      name: "Beginner risk mistakes list",
      ideaId: "idea-risk",
      videoId: "cv-001",
      topic: "Risk management",
      format: "Long-form",
      hypothesis: "Mistake lists still work if the first item is unexpected.",
      published: "Aug 12",
      v24: 9180,
      v7: 24100,
      retention: 69,
      subs: 41,
      result: "Best conversion in the set",
      decision: "GO",
      lesson: "Trading mistakes are GO for Christina even when market signal is only Moderate.",
      next: "Repeat mistake structure on position sizing.",
      status: "Published",
    },
    {
      id: "EXP-005",
      name: "Shorts die at 500",
      ideaId: "idea-shorts",
      videoId: null,
      topic: "Creator growth",
      format: "Short",
      hypothesis: "Diagnosis beats motivation in creator-growth shorts.",
      published: "—",
      v24: null,
      v7: null,
      retention: null,
      subs: null,
      result: "Awaiting publish",
      decision: "TEST",
      lesson: "",
      next: "Publish and measure 24h retention.",
      status: "Ready",
    },
    {
      id: "EXP-006",
      name: "Build in public without performing",
      ideaId: "idea-bip",
      videoId: null,
      topic: "Build in public",
      format: "Long-form",
      hypothesis: "Honest process converts better than highlight reels.",
      published: "—",
      v24: null,
      v7: null,
      retention: null,
      subs: null,
      result: "Recorded, not live",
      decision: "HOLD",
      lesson: "",
      next: "Hold until EXP-004 follow-up ships.",
      status: "Recorded",
    },
  ];

  const myVideos = [
    {
      id: "cv-004",
      title: "Why Two Traders Copying the Same Signal Get Different Results",
      date: "Sep 14",
      type: "Short",
      views: 18640,
      v24: 7420,
      v7: 18640,
      likes: 940,
      comments: 126,
      subs: 38,
      retention: 71,
      ctr: 8.4,
      exp: "EXP-004",
      decision: "GO",
    },
    {
      id: "cv-003",
      title: "Why copied signals give different results",
      date: "Sep 7",
      type: "Long-form",
      views: 15420,
      v24: 6800,
      v7: 15420,
      likes: 612,
      comments: 88,
      subs: 22,
      retention: 64,
      ctr: 6.1,
      exp: "EXP-003",
      decision: "TEST",
    },
    {
      id: "cv-002",
      title: "I Built a Research Desk With AI in 24 Hours",
      date: "Aug 28",
      type: "Long-form",
      views: 9800,
      v24: 4120,
      v7: 9800,
      likes: 401,
      comments: 67,
      subs: 11,
      retention: 58,
      ctr: 5.4,
      exp: "EXP-002",
      decision: "TEST",
    },
    {
      id: "cv-001",
      title: "5 Risk Management Mistakes Beginners Make",
      date: "Aug 12",
      type: "Long-form",
      views: 24100,
      v24: 9180,
      v7: 24100,
      likes: 1102,
      comments: 174,
      subs: 41,
      retention: 69,
      ctr: 7.2,
      exp: "EXP-001",
      decision: "GO",
    },
  ];

  const savedSeed = ["v-copy", "v-ai24", "v-signals", "v-shorts", "v-journal"];

  return { videos, ideas, experiments, myVideos, savedSeed, thumb };
})();
